### ISSUE TITLE
Fail on CLI execute

### ISSUE THREAD

**Issue by welbert** [jxom/get-latest-release#1]
I'm try execute `get-latest-release -r caprine -o sindresorhus -e dmg` or simple `get-latest-release`

And i got this message
```
/usr/lib/node_modules/get-latest-release/cli.js:36
const handleCLI = async () => {
                        ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
```

Version: 1.1.1
O.S.: Debian

**Comment by jxom** [comment]
What version of node are you running? This currently only works for versions of Node higher than or equal to 7.6.0

**Comment by welbert** [comment]
Oh, im using 6.9.1.
Ok, no problem
